# -*- coding: utf-8 -*-
"""
Created on Wed Nov  2 20:50:08 2022

@author: stamhane
"""
# Section start
# This code must be kept in the beginning of the file.
# This section of code must be run only once

import pymongo
from bson.objectid import ObjectId     # This is required for accessing objects via default ID

myclient = pymongo.MongoClient()            
# Creates the mongoDB client. The default parameter sets it to http://localhost:27017/
# For deploying it to cloud, connection string should be passed which is similar to
# mongodb+srv://<username>:<password>@<username>.umrrjlu.mongodb.net/?retryWrites=true&w=majority
# Note: "<>" should be removed from the string


mydb = myclient["sort_file_db"]
# This creates the database


overall_col = mydb["overall_col"]            #overall_col includes input_loc, output_loc and tags
detailed_col = mydb["detailed_col"]         # detailed_col includes tag_name, action, SID and file_uid
# This creates the collection in which records will be stored

# Section end




# Section start

# This section should be placed where the operations are going to take place
# For now, a unique ID is generated by MongoDB itself, if anything else is needed, it needs to be specified

# For inserting data in the file
# This is an example code given. For inserting multiple data, use insert_many()

# For overall collection
overall_dict = {"input_loc": "INPUT LOCATION", "output_loc": "OUTPUT LOCATION", 
          "tags": {"MediaStorageSOPInstanceUID": "media id"}}
x = overall_col.insert_one(overall_dict)
print(x.inserted_id)

# For detailed collection
detailed_dict = {"tag_name": "the tag name", "action": "action to be performed",
                 "series_instance_uid": "The SID", "file_uid": "The file UID"}
x = detailed_col.insert_one(detailed_dict)
print(x.inserted_id)


# For finding/printing out all data
for x in overall_col.find():
    print(x)
    
for x in detailed_col.find():
    print(x)

# =============================================================================
# The sample data aove will be inserted when the file is run.
# Run this chunk of code to delete that data from the database by replacing #id with real id
# 
# x = overall_col.delete_one({'_id': ObjectId('#id')})
# print(x.deleted_count)

# x = detailed_col.delete_one({'_id': ObjectId('#id')})
# print(x.deleted_count)
# 
# 
# =============================================================================

# Section end



# Section start

# This section of code must be placed at the end of the file
# This section of code must be run only once

myclient.close()

# Section end